# Generated by Django 3.0.7 on 2020-09-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelFKTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModelFKSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_field', models.CharField(max_length=50)),
                ('fk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_sources', to='testcases.TestModelFKTarget')),
                ('one_to_one_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestModelFKTarget')),
            ],
        ),
    ]
