name: Publish on test PyPI

on:
  push:
    branches: [ release-test-pypi ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version

    - name: Retrieve latest version from Test PyPI and bump
      run: |
        curl -L -s "https://test.pypi.org/pypi/simple-api/json" | jq  -r '.releases | keys | .[]' | sort -V | tail -1 > VERSION
        bump2version --current-version $(cat VERSION) patch VERSION
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
